SELECT  COUNT(DISTINCT EMPLID ) FROM PS_TRAINING;

SELECT  COUNT(DISTINCT EMPLID || COURSE ) FROM PS_TRAINING;

SELECT  COUNT(DISTINCT EMPLID || COURSE || SESSION_NBR) FROM PS_TRAINING;

SELECT  COUNT(*) FROM PS_TRAINING;
